### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create the base html for the page.
- [x] Add in the necessary CSS rule sets.
- [x] Test and remove any unused CSS. 

![issue1](https://user-images.githubusercontent.com/53131688/120697575-85ccb280-c473-11eb-80ab-bfa07bf516c4.gif)
