### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create turn classes in CSS
- [x] Create main.js file
- [x] link it to the html with the script tag
- [x] add eventlisteners for arrow key presses that turn the icon.
- [x] test the turning functions

![issue2](https://user-images.githubusercontent.com/53131688/120697501-69307a80-c473-11eb-96a1-d1f7edd71c52.gif)
