### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add more directions to the drive function.
- [x] test the driving and steering. 
- [x] Ship change function added.
- [x] Galaxy change function added.

![issue5](https://user-images.githubusercontent.com/53131688/120697801-c9bfb780-c473-11eb-8295-f22236147d9c.gif)
